import Like from "../../../img/Like.svg";
import Comment from "../../../img/Comment.svg";
import test1 from "../../../img/test1.png";
import test2 from "../../../img/test2.png";
import test3 from "../../../img/test3.png";
import test4 from "../../../img/test4.png";
import test5 from "../../../img/test5.png";
import test6 from "../../../img/test6.png";
import test7 from "../../../img/test7.png";
import test8 from "../../../img/test8.png";

const dataCardCatalog = [
  {
    img: test1,
    day: "Today",
    date: "9-08-2016",
    title: "Secure Fish Trading",
    likeIcon: Like,
    quantityLike: "128",
    iconComment: Comment,
    quantityComment: "31",
    repeatIconLike: Like,
    repeatIconComment: Comment,
    repeatQuantityLike: "67",
    repeatQuantityComment: "22",
    onDateDownload: "Image upload",
    dateDownload: "11-04-2016",
    id: 27273,
  },
  {
    img: test2,
    day: "Today",
    date: "9-08-2016",
    title: "Secure Fish Trading",
    likeIcon: Like,
    quantityLike: "128",
    iconComment: Comment,
    quantityComment: "31",
    repeatIconLike: Like,
    repeatIconComment: Comment,
    repeatQuantityLike: "67",
    repeatQuantityComment: "22",
    onDateDownload: "Image upload",
    dateDownload: "11-04-2016",
    id: 2727232,
  },
  {
    img: test3,
    day: "Today",
    date: "9-08-2016",
    title: "Secure Fish Trading",
    likeIcon: Like,
    quantityLike: "128",
    iconComment: Comment,
    quantityComment: "31",
    repeatIconLike: Like,
    repeatIconComment: Comment,
    repeatQuantityLike: "67",
    repeatQuantityComment: "22",
    onDateDownload: "Image upload",
    dateDownload: "11-04-2016",
    id: 2726713,
  },
  {
    img: test4,
    day: "Today",
    date: "9-08-2016",
    title: "Secure Fish Trading",
    likeIcon: Like,
    quantityLike: "128",
    iconComment: Comment,
    quantityComment: "31",
    repeatIconLike: Like,
    repeatIconComment: Comment,
    repeatQuantityLike: "67",
    repeatQuantityComment: "22",
    onDateDownload: "Image upload",
    dateDownload: "11-04-2016",
    id: 2727399,
  },
  {
    img: test5,
    day: "Today",
    date: "9-08-2016",
    title: "Secure Fish Trading",
    likeIcon: Like,
    quantityLike: "128",
    iconComment: Comment,
    quantityComment: "31",
    repeatIconLike: Like,
    repeatIconComment: Comment,
    repeatQuantityLike: "67",
    repeatQuantityComment: "22",
    onDateDownload: "Image upload",
    dateDownload: "11-04-2016",
    id: 2727311,
  },
  {
    img: test6,
    day: "Today",
    date: "9-08-2016",
    title: "Secure Fish Trading",
    likeIcon: Like,
    quantityLike: "128",
    iconComment: Comment,
    quantityComment: "31",
    repeatIconLike: Like,
    repeatIconComment: Comment,
    repeatQuantityLike: "67",
    repeatQuantityComment: "22",
    onDateDownload: "Image upload",
    dateDownload: "11-04-2016",
    id: 27273221,
  },
  {
    img: test7,
    day: "Today",
    date: "9-08-2016",
    title: "Secure Fish Trading",
    likeIcon: Like,
    quantityLike: "128",
    iconComment: Comment,
    quantityComment: "31",
    repeatIconLike: Like,
    repeatIconComment: Comment,
    repeatQuantityLike: "67",
    repeatQuantityComment: "22",
    onDateDownload: "Image upload",
    dateDownload: "11-04-2016",
    id: 27273331,
  },
  {
    img: test8,
    day: "Today",
    date: "9-08-2016",
    title: "Secure Fish Trading",
    likeIcon: Like,
    quantityLike: "128",
    iconComment: Comment,
    quantityComment: "31",
    repeatIconLike: Like,
    repeatIconComment: Comment,
    repeatQuantityLike: "67",
    repeatQuantityComment: "22",
    onDateDownload: "Image upload",
    dateDownload: "11-04-2016",
    id: 27273441,
  },
];

export default dataCardCatalog;
